# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deletewindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QWidget
import pymysql
import os


class Ui_Delete(QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1221, 1040)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 20, 481, 111))
        self.label.setStyleSheet("font: 48pt \\\"微软雅黑\\\";")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 170, 461, 80))
        self.widget.setObjectName("widget")
        self.ID_label = QtWidgets.QLabel(self.widget)
        self.ID_label.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.ID_label.setStyleSheet("font: 24pt \\\"微软雅黑\\\";")
        self.ID_label.setObjectName("ID_label")
        self.ID_textEdit = QtWidgets.QTextEdit(self.widget)
        self.ID_textEdit.setGeometry(QtCore.QRect(90, 0, 351, 71))
        self.ID_textEdit.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.ID_textEdit.setObjectName("ID_textEdit")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(40, 270, 461, 80))
        self.widget_2.setObjectName("widget_2")
        self.name_label = QtWidgets.QLabel(self.widget_2)
        self.name_label.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.name_label.setStyleSheet("font: 24pt \\\"微软雅黑\\\";")
        self.name_label.setObjectName("name_label")
        self.name_textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.name_textEdit.setGeometry(QtCore.QRect(110, 0, 331, 71))
        self.name_textEdit.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.name_textEdit.setObjectName("name_textEdit")
        self.result_textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.result_textBrowser.setGeometry(QtCore.QRect(590, 210, 601, 581))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.result_textBrowser.setFont(font)
        self.result_textBrowser.setObjectName("result_textBrowser")
        self.delete_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.delete_pushButton.setGeometry(QtCore.QRect(40, 880, 561, 91))
        self.delete_pushButton.setStyleSheet("font: 24pt \\\"微软雅黑\\\";")
        self.delete_pushButton.setObjectName("delete_pushButton")
        self.delete_pushButton.clicked.connect(self.delete)
        self.return_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.return_pushButton.setGeometry(QtCore.QRect(620, 880, 561, 91))
        self.return_pushButton.setStyleSheet("font: 24pt \\\"微软雅黑\\\";")
        self.return_pushButton.setObjectName("return_pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 140, 1241, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(40, 470, 461, 80))
        self.widget_3.setObjectName("widget_3")
        self.nation_label = QtWidgets.QLabel(self.widget_3)
        self.nation_label.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.nation_label.setStyleSheet("font: 24pt \\\"微软雅黑\\\";")
        self.nation_label.setObjectName("nation_label")
        self.nation_textEdit = QtWidgets.QTextEdit(self.widget_3)
        self.nation_textEdit.setGeometry(QtCore.QRect(110, 0, 331, 71))
        self.nation_textEdit.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.nation_textEdit.setObjectName("nation_textEdit")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(40, 570, 461, 80))
        self.widget_4.setObjectName("widget_4")
        self.position_label = QtWidgets.QLabel(self.widget_4)
        self.position_label.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.position_label.setStyleSheet("font: 24pt \\\"微软雅黑\\\";")
        self.position_label.setObjectName("position_label")
        self.position_textEdit = QtWidgets.QTextEdit(self.widget_4)
        self.position_textEdit.setGeometry(QtCore.QRect(110, 0, 331, 71))
        self.position_textEdit.setStyleSheet("font: 12pt \\\"微软雅黑\\\";")
        self.position_textEdit.setObjectName("position_textEdit")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 840, 1221, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(533, 150, 20, 701))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(40, 370, 461, 80))
        self.widget_5.setObjectName("widget_5")
        self.gender_label = QtWidgets.QLabel(self.widget_5)
        self.gender_label.setGeometry(QtCore.QRect(10, 10, 101, 51))
        self.gender_label.setStyleSheet("font: 24pt \\\"微软雅黑\\\";")
        self.gender_label.setObjectName("gender_label")
        self.man_radioButton = QtWidgets.QRadioButton(self.widget_5)
        self.man_radioButton.setGeometry(QtCore.QRect(180, 10, 115, 19))
        self.man_radioButton.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.man_radioButton.setObjectName("man_radioButton")
        self.woman_radioButton = QtWidgets.QRadioButton(self.widget_5)
        self.woman_radioButton.setGeometry(QtCore.QRect(180, 50, 115, 19))
        self.woman_radioButton.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.woman_radioButton.setObjectName("woman_radioButton")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(40, 670, 461, 161))
        self.widget_6.setObjectName("widget_6")
        self.kind_label = QtWidgets.QLabel(self.widget_6)
        self.kind_label.setGeometry(QtCore.QRect(20, 50, 311, 61))
        self.kind_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.kind_label.setObjectName("kind_label")
        self.kind_radioButton_1 = QtWidgets.QRadioButton(self.widget_6)
        self.kind_radioButton_1.setGeometry(QtCore.QRect(300, 20, 131, 19))
        self.kind_radioButton_1.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.kind_radioButton_1.setObjectName("kind_radioButton_1")
        self.kind_radioButton_2 = QtWidgets.QRadioButton(self.widget_6)
        self.kind_radioButton_2.setGeometry(QtCore.QRect(300, 70, 131, 19))
        self.kind_radioButton_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.kind_radioButton_2.setObjectName("kind_radioButton_2")
        self.kind_radioButton_3 = QtWidgets.QRadioButton(self.widget_6)
        self.kind_radioButton_3.setGeometry(QtCore.QRect(300, 120, 131, 19))
        self.kind_radioButton_3.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.kind_radioButton_3.setObjectName("kind_radioButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1221, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def delete(self):

        ID = self.ID_textEdit.toPlainText()
        name = self.name_textEdit.toPlainText()
        gender = ''
        if(self.man_radioButton.isChecked() == True):
            gender = '男'
        elif(self.woman_radioButton.isChecked() == True):
            gender = '女'
        nation = self.nation_textEdit.toPlainText()
        position = self.position_textEdit.toPlainText()
        kind = ''
        if (self.kind_radioButton_1.isChecked() == True):
            kind = '口腔全景片'
        elif(self.kind_radioButton_2.isChecked() == True):
            kind = '头颅侧位片'
        elif(self.kind_radioButton_3.isChecked() == True):
            kind = 'CBCT'

        if os.path.isfile('../bin/settings.txt'):
            f = open('../bin/settings.txt', 'r')
            settings = f.readlines()
            host = settings[0].strip()
            port = int(settings[1].replace('\n', ''))
            user = settings[2].replace('\n', '')
            pswd = settings[3].replace('\n', '')
            db_name = settings[4].replace('\n', '')
            table = settings[5].replace('\n', '')
        else:
            self.result_textBrowser.setText("数据库错误")

        # 打开数据库连接
        try:
            db = pymysql.connect(host=host, user=user, passwd=pswd, port=port, db=db_name)
            print('连接成功！')
        except:
            print('something wrong!')

        # 使用 cursor() 方法创建一个游标对象 cursor
        cursor = db.cursor()

        # SQL 删除语句
        sql = "DELETE FROM "+ table +" WHERE "
        if(ID != '0'):
            sql =sql + "id = "+ID+" AND "
        else:
            sql = sql + "id !="+ID+" AND "
        if(name != ''):
            sql = sql+"name = '"+name+"' AND "
        else:
            sql =sql+"name != '"+name+"' AND "
        if (gender != ''):
            sql = sql + "gender = '" + gender + "' AND "
        else:
            sql = sql + "gender != '" + gender + "' AND "
        if (nation != ''):
            sql = sql + "nation = '" + nation + "' AND "
        else:
            sql = sql + "nation != '" + nation + "' AND "
        if (position != ''):
            sql = sql + "position = '" + position + "' AND "
        else:
            sql = sql + "position != '" + position + "' AND "
        if (kind != ''):
            sql = sql + "kind = '" + kind + "'"
        else:
            sql = sql + "kind != '" + kind + "'"
        print(sql)

        try:
            # 执行SQL语句
            cursor.execute(sql)
            # 提交修改
            db.commit()
            print('数据删除成功')
            self.result_textBrowser.setText('数据删除成功')
        except:
            # 发生错误时回滚
            db.rollback()
            print('数据删除失败')
            self.result_textBrowser.setText('数据删除失败')


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        Form.setWindowTitle(_translate("Form", "口腔头颈影像数据库管理窗口"))
        self.label.setText(_translate("Form", "删除影像资料"))
        self.ID_label.setText(_translate("Form", "ID："))
        self.ID_textEdit.setText(_translate("Form", "0"))
        self.name_label.setText(_translate("Form", "姓名："))
        self.delete_pushButton.setText(_translate("Form", "删除"))
        self.return_pushButton.setText(_translate("Form", "返回上一页"))
        self.nation_label.setText(_translate("Form", "民族："))
        self.position_label.setText(_translate("Form", "地区："))
        self.gender_label.setText(_translate("Form", "性别："))
        self.man_radioButton.setText(_translate("Form", "男"))
        self.woman_radioButton.setText(_translate("Form", "女"))
        self.kind_label.setText(_translate("Form", "影像资料类型："))
        self.kind_radioButton_1.setText(_translate("Form", "口腔全景片"))
        self.kind_radioButton_2.setText(_translate("Form", "头颅侧位片"))
        self.kind_radioButton_3.setText(_translate("Form", "CBCT"))
