# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'insertwindow_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QWidget
import pymysql
import os

class Ui_Insert_1(QWidget):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1242, 1038)
        self.title = QtWidgets.QLabel(Form)
        self.title.setGeometry(QtCore.QRect(370, 0, 481, 91))
        self.title.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"font: 75 48pt \"微软雅黑\";")
        self.title.setObjectName("title")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(40, 100, 1181, 61))
        self.widget.setObjectName("widget")
        self.location_textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.location_textBrowser.setGeometry(QtCore.QRect(10, 10, 1001, 41))
        self.location_textBrowser.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.location_textBrowser.setObjectName("location_textBrowser")
        self.location_pushButton = QtWidgets.QPushButton(self.widget)
        self.location_pushButton.setGeometry(QtCore.QRect(1030, 20, 93, 28))
        self.location_pushButton.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.location_pushButton.setObjectName("location_pushButton")
        self.location_pushButton.clicked.connect(self.locate)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(110, 280, 301, 81))
        self.widget_2.setObjectName("widget_2")
        self.age_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.age_doubleSpinBox.setGeometry(QtCore.QRect(150, 30, 121, 41))
        self.age_doubleSpinBox.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.age_doubleSpinBox.setObjectName("age_doubleSpinBox")
        self.age_label = QtWidgets.QLabel(self.widget_2)
        self.age_label.setGeometry(QtCore.QRect(10, 10, 101, 71))
        self.age_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.age_label.setObjectName("age_label")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(110, 370, 301, 81))
        self.widget_3.setObjectName("widget_3")
        self.man_button = QtWidgets.QRadioButton(self.widget_3)
        self.man_button.setGeometry(QtCore.QRect(150, 10, 115, 19))
        self.man_button.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.man_button.setObjectName("man_button")
        self.woman_button = QtWidgets.QRadioButton(self.widget_3)
        self.woman_button.setGeometry(QtCore.QRect(150, 60, 115, 19))
        self.woman_button.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.woman_button.setObjectName("woman_button")
        self.gender_label = QtWidgets.QLabel(self.widget_3)
        self.gender_label.setGeometry(QtCore.QRect(10, 10, 111, 51))
        self.gender_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.gender_label.setObjectName("gender_label")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(110, 460, 301, 91))
        self.widget_4.setObjectName("widget_4")
        self.ID_label = QtWidgets.QLabel(self.widget_4)
        self.ID_label.setGeometry(QtCore.QRect(0, 20, 71, 51))
        self.ID_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.ID_label.setObjectName("ID_label")
        self.ID_textEdit = QtWidgets.QTextEdit(self.widget_4)
        self.ID_textEdit.setGeometry(QtCore.QRect(70, 30, 221, 41))
        self.ID_textEdit.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.ID_textEdit.setObjectName("ID_textEdit")
        self.insert_pushButton = QtWidgets.QPushButton(Form)
        self.insert_pushButton.setGeometry(QtCore.QRect(30, 970, 921, 41))
        self.insert_pushButton.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.insert_pushButton.setObjectName("insert_pushButton")
        self.insert_pushButton.clicked.connect(self.insert)
        self.return_pushButton = QtWidgets.QPushButton(Form)
        self.return_pushButton.setGeometry(QtCore.QRect(1010, 970, 181, 41))
        self.return_pushButton.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.return_pushButton.setObjectName("return_pushButton")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(110, 180, 301, 91))
        self.widget_5.setObjectName("widget_5")
        self.name_label = QtWidgets.QLabel(self.widget_5)
        self.name_label.setGeometry(QtCore.QRect(10, 20, 101, 51))
        self.name_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.name_label.setObjectName("name_label")
        self.name_textEdit = QtWidgets.QTextEdit(self.widget_5)
        self.name_textEdit.setGeometry(QtCore.QRect(120, 30, 181, 41))
        self.name_textEdit.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.name_textEdit.setObjectName("name_textEdit")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(110, 660, 301, 91))
        self.widget_6.setObjectName("widget_6")
        self.position_label = QtWidgets.QLabel(self.widget_6)
        self.position_label.setGeometry(QtCore.QRect(10, 20, 101, 51))
        self.position_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.position_label.setObjectName("position_label")
        self.position_textEdit = QtWidgets.QTextEdit(self.widget_6)
        self.position_textEdit.setGeometry(QtCore.QRect(120, 30, 181, 41))
        self.position_textEdit.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.position_textEdit.setObjectName("position_textEdit")
        self.widget_7 = QtWidgets.QWidget(Form)
        self.widget_7.setGeometry(QtCore.QRect(110, 560, 301, 91))
        self.widget_7.setObjectName("widget_7")
        self.nation_label = QtWidgets.QLabel(self.widget_7)
        self.nation_label.setGeometry(QtCore.QRect(10, 20, 101, 51))
        self.nation_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.nation_label.setObjectName("nation_label")
        self.nation_textEdit = QtWidgets.QTextEdit(self.widget_7)
        self.nation_textEdit.setGeometry(QtCore.QRect(120, 30, 181, 41))
        self.nation_textEdit.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.nation_textEdit.setObjectName("nation_textEdit")
        self.result_textBrowser = QtWidgets.QTextBrowser(Form)
        self.result_textBrowser.setGeometry(QtCore.QRect(550, 180, 651, 771))
        self.result_textBrowser.setObjectName("result_textBrowser")
        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setGeometry(QtCore.QRect(10, 760, 511, 181))
        self.widget_8.setObjectName("widget_8")
        self.kind_label = QtWidgets.QLabel(self.widget_8)
        self.kind_label.setGeometry(QtCore.QRect(10, 60, 251, 51))
        self.kind_label.setStyleSheet("font: 24pt \"微软雅黑\";")
        self.kind_label.setObjectName("kind_label")
        self.kind_radioButton_1 = QtWidgets.QRadioButton(self.widget_8)
        self.kind_radioButton_1.setGeometry(QtCore.QRect(310, 30, 131, 21))
        self.kind_radioButton_1.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.kind_radioButton_1.setObjectName("kind_radioButton_1")
        self.kind_radioButton_2 = QtWidgets.QRadioButton(self.widget_8)
        self.kind_radioButton_2.setGeometry(QtCore.QRect(310, 80, 131, 19))
        self.kind_radioButton_2.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.kind_radioButton_2.setObjectName("kind_radioButton_2")
        self.kind_radioButton_3 = QtWidgets.QRadioButton(self.widget_8)
        self.kind_radioButton_3.setGeometry(QtCore.QRect(310, 130, 115, 19))
        self.kind_radioButton_3.setStyleSheet("font: 12pt \"微软雅黑\";")
        self.kind_radioButton_3.setObjectName("kind_radioButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def locate(self):
        location = QtWidgets.QFileDialog.getOpenFileName(None, "选取图片", "C:/")  # 起始路径
        location = str(location)
        location = location.replace('(','')
        location = location.replace(')','')
        location = location.replace(',','')
        location = location.replace("'",'')
        location = location.replace('All Files *','')
        location = location.strip()
        self.location_textBrowser.setText(location)

    def insert(self):

        ID = self.ID_textEdit.toPlainText()
        name = self.name_textEdit.toPlainText()
        gender = ''
        if (self.man_button.isChecked()==True):
            gender = '男'
        if (self.woman_button.isChecked() == True):
            gender = '女'
        age = str(self.age_doubleSpinBox.value())
        nation = self.nation_textEdit.toPlainText()
        position = self.position_textEdit.toPlainText()
        location = self.location_textBrowser.toPlainText()
        if (self.kind_radioButton_1.isChecked() == True):
            kind = '口腔全景片'
        elif (self.kind_radioButton_2.isChecked() == True):
            kind = '头颅侧位片'
        elif (self.kind_radioButton_3.isChecked() == True):
            kind = 'CBCT'
        else:
            kind = ''

        if  os.path.isfile('../bin/settings.txt'):
            f = open('../bin/settings.txt', 'r')
            settings = f.readlines()
            host = settings[0].strip()
            port = int(settings[1].replace('\n',''))
            user = settings[2].replace('\n','')
            pswd = settings[3].replace('\n','')
            db_name = settings[4].replace('\n','')
            table = settings[5].replace('\n','')
        else:
            self.result_textBrowser.setText("数据库错误")

        # 打开数据库连接
        try:
            db = pymysql.connect(host=host, user=user, passwd=pswd, port=port, db=db_name)
            print('连接成功！')
        except:
            print('something wrong!')

        # 使用 cursor() 方法创建一个游标对象 cursor
        cursor = db.cursor()

        # SQL 插入语句
        sql = "INSERT INTO " + table + "(id,name,gender,age,nation,position,location,kind) VALUES (%s, '%s', '%s', %s, '%s','%s','%s','%s')"%(ID,name,gender,age,nation,position,location,kind)
        try:
            # 执行sql语句
            cursor.execute(sql)
            # 提交到数据库执行
            db.commit()
            print('数据插入成功！')
            self.result_textBrowser.setText('数据插入成功！\n'
                                            'ID:' + ID+ '\n'
                                            '姓名:' + name + '\n'
                                            '性别:' + gender + '\n'
                                            '年龄:' + age + '\n'
                                            '民族:' + nation +'\n'
                                            '地区:' + position + '\n'
                                            '影像资料类型:' + kind
                                            )
        except:
            # 如果发生错误则回滚
            db.rollback()
            print('数据插入错误！')
            self.result_textBrowser.setText('数据插入错误！')

        # 关闭数据库连接
        db.close()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        Form.setWindowTitle(_translate("Form", "口腔头颈影像数据库管理窗口"))
        self.title.setText(_translate("Form", "增加影像资料"))
        self.location_pushButton.setText(_translate("Form", "选择"))
        self.age_label.setText(_translate("Form", "年龄："))
        self.man_button.setText(_translate("Form", "男"))
        self.woman_button.setText(_translate("Form", "女"))
        self.gender_label.setText(_translate("Form", "性别："))
        self.ID_label.setText(_translate("Form", "ID："))
        self.insert_pushButton.setText(_translate("Form", "确定"))
        self.return_pushButton.setText(_translate("Form", "返回上一页"))
        self.name_label.setText(_translate("Form", "姓名："))
        self.position_label.setText(_translate("Form", "地区："))
        self.nation_label.setText(_translate("Form", "民族："))
        self.kind_label.setText(_translate("Form", "影像资料类型:"))
        self.kind_radioButton_1.setText(_translate("Form", "口腔全景片"))
        self.kind_radioButton_2.setText(_translate("Form", "头颅侧位片"))
        self.kind_radioButton_3.setText(_translate("Form", "CBCT"))
